.equ ADJUST_BUTTON = PB0
.equ SELECTION_BUTTON = PB1
.def AUX = R16 

SETUP:
; Sets PORTB as output
LDI AUX,0xFF
OUT DDRD,AUX
  
; Sets PORTB as input
LDI AUX, 0x00
OUT DDRB, AUX
  
; Enable pull-up to PORTD
LDI AUX,0xFF
OUT PORTD,AUX
  
; Enable pull-up to PORTD
LDI AUX, 0xFF
OUT PORTB, AUX

; Turn off all LEDs
START:
  LDI AUX, 0xFF
  OUT PORTD, AUX

; If ADJUST_BUTTON is pressed turn on LEDs 0..3
ADJUST_VALIDATION:
  SBIC PINB, ADJUST_BUTTON
  RJMP SELECTION_VALIDATION
  LDI AUX, 0xF0
  OUT PORTD, AUX

; If SELECTION_BUTTON is pressed turn on LEDs 4..7
SELECTION_VALIDATION:
  SBIC PINB, SELECTION_BUTTON
  RJMP START
  LDI AUX, 0x0F
  OUT PORTD, AUX
  
  RJMP START